### ISSUE TITLE
How to handle a database Timeout

### ISSUE THREAD

**Issue by BigHoss** [Hinni/seq-input-mssql#12]
I query a view that does a few count statements.

When we ran it last week it took about 13sec in ssms. now its up to 26sec.

And in Seq we get the following error message: 

![image](https://user-images.githubusercontent.com/932436/135845838-66379e65-380c-4cd5-a50a-8160b4cb954e.png)

A workaround i was thinking about was to do this query with an agentjob and write the result to a table and query this.

**Comment by MattMofDoom** [comment]
@BigHoss  I think it would be reasonable to have a timeout config, and there's a few other connection params that would be useful. I'll prepare a PR for @Hinni to review after I've tested changes 😊

In terms of agent jobs, I'm going to do a blog post on how to turn agent job logs into a Seq view via MSSQL Input - it's insanely useful.

**Comment by MattMofDoom** [comment]
@BigHoss  I've added PR #13 which will add connection and command (query) timeout settings, and ensures queries won't overlap ... just pending @Hinni  to review & merge.

In the meantime, I've also written up how to turn SQL agent job logs into Seq logs using MSSQL Input 😁 Here's the link: https://mattmofdoom.com/using-seqinputmssql-to-read-sql-job-agent-tables-as-logs/

Cheers,

Matt

**Comment by BigHoss** [comment]
@MattMofDoom Thanks a lot.
