### ISSUE TITLE
Option: Level from database to override configured level 

### ISSUE THREAD

**Issue by EdwinRoestenburg** [Hinni/seq-input-mssql#8]
Currently all entries get e fixed level in Seq. This level gets set during configuration.
It would be nice if there was an extra option to obtain the level from the database, so that the original level gets used rather that the one configured during setup.

**Comment by Hinni** [comment]
Hi @EdwinRoestenburg 

Thank you for your input. I was faced with the same requirement.
My approach to fulfill this looks as follows:

- One instance to fetch all filtered SQL entries with info level in table A
- Another instance to fetch all filtered SQL entries with error level in table A

**Pros**
- Use a specific filter clause for each log level
- Complexity to configure each instance is lower

**Cons**
- More running instances which have a memory footprint to your Seq server

Is this a possible solution for you?

**Comment by EdwinRoestenburg** [comment]
That would certainly work, but I was hoping not having to create multiple instances just for getting the right level, which is already available in de database. If the tool could simply read the correct column, take the level and apply that when injecting into Seq, that would be easier 😊

 

But I can see that it takes time to build, and that comes with some complexities (like knowing which column and things like what to do if the level in de DB column are incorrectly named, etc….).

 

Anyway, if ever you feel bored 😊, it would be a nice feature to have.

Until then I’ll go with the option you outlined in your response.

 

Thanks,

 

Edwin Roestenburg.
